engineStrict: true
minimumReleaseAge: 4320 # 72 hours
minimumReleaseAgeExcludePrune: true
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
overrides:
  sharp@<0.35.4: ^0.35.4
